# Generated by Django 5.0.3 on 2024-08-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logo")),
                ("posted_jobs", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                (
                    "profile_image",
                    models.ImageField(null=True, upload_to="profile_image"),
                ),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("skills", models.CharField(blank=True, max_length=255, null=True)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "exeperience",
                    models.IntegerField(
                        blank=True, default=0, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "employment_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("skills", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobApp.company",
                    ),
                ),
            ],
        ),
    ]
