# Generated by Django 5.0.3 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0003_job_company_appliedjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.CharField(max_length=100),
        ),
    ]
