# Generated by Django 5.0.3 on 2024-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JobApp", "0005_alter_user_mobile_companyuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resume/"),
        ),
    ]
